version: 2.1

orbs:
  windows: circleci/windows@5.0.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run dotnet format check"
          command: dotnet format --verify-no-changes
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "ZDrive/zdrive-back.csproj" }}{{ checksum "ZDrive-Test/ZDrive-Test.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "ZDrive/zdrive-back.csproj" }}{{ checksum "ZDrive-Test/ZDrive-Test.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage" --logger "junit;LogFilePath=./results.xml"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_test_results:
          path: ZDrive-Test
      - store_artifacts:
          path: test_coverage

  deploy:
    description: Deploy application to test server
    machine:
      enabled: true
    steps:
      - run:
          name: Change Branch To Current
          command: ssh $SSH_MERSERVER_USER@$SSH_MERSERVER_HOST -o ProxyCommand="ssh $SSH_CATSERVER_USER@$SSH_CATSERVER_HOST -p 443 -W %h:%p" "./switch-branch.sh << pipeline.git.branch >>"
      - run:
          name: Build and Run Docker Image
          command: ssh $SSH_MERSERVER_USER@$SSH_MERSERVER_HOST -o ProxyCommand="ssh $SSH_CATSERVER_USER@$SSH_CATSERVER_HOST -p 443 -W %h:%p" "./zdrive-build.sh"

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - release/1.0